drop table if exists tb_client cascade;
drop table if exists tb_order cascade;
drop table if exists tb_order_item cascade;
drop table if exists tb_product cascade;

create table tb_client
(
    id    bigint generated by default as identity,
    email varchar(255) not null,
    name  varchar(255) not null,
    city  varchar(255) not null,
    home_number  varchar(255) not null,
    phone_number  varchar(255) not null,
    state  varchar(255) not null,
    street_name  varchar(255) not null,
    zip_code  varchar(255) not null,
    primary key (id)
);

create table tb_order
(
    id        bigint generated by default as identity,
    moment    timestamp(6) with time zone not null,
    status    smallint                    not null,
    client_id bigint,
    primary key (id)
);

create table tb_order_item
(
    id         bigint generated by default as identity,
    price      float(53) not null,
    quantity   integer   not null,
    order_id   bigint,
    product_id bigint,
    primary key (id)
);

create table tb_product
(
    id    bigint generated by default as identity,
    name  varchar(255) not null,
    price float(53)    not null,
    quantity   integer   not null,
    primary key (id)
);

alter table if exists tb_order
    add constraint FK_order_client
        foreign key (client_id)
            references tb_client;

alter table if exists tb_order_item
    add constraint FK_order_item_order
        foreign key (order_id)
            references tb_order;

alter table if exists tb_order_item
    add constraint FK_order_item_product
        foreign key (product_id)
            references tb_product;


INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Oleg Sentsov', 'test1@gmail.com', 'Kyiv', '123', '80504340444', 'UA', 'Tyu', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Mila Kunis', 'test2@gmail.com', 'Kyiv', '750', '80504340445', 'UA', 'Fts', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Sergiy Rebrov', 'test3@gmail.com', 'Kyiv', '336', '80504340446', 'UA', 'Cert', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Lesya Ukrainka', 'test4@gmail.com', 'Chernivtsi', '666', '80504340447', 'UA', 'Ert', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Serhiy Korol', 'test5@gmail.com', 'Chernivtsi', '777', '80504340448', 'UA', 'Rzo', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Daria Bilodid', 'test6@gmail.com', 'Chernivtsi', '483', '80504340449', 'UA', 'Rds', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Oksana Baiul', 'test7@gmail.com', 'Lviv', '125', '80504340440', 'UA', 'Agh', '5700');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Taras hevchenko', 'test8@gmail.com', 'Lviv', '046', '80504340441', 'UA', 'Fgd', '5700');

INSERT INTO tb_order (moment, status, client_id)
VALUES ('2023-09-01T23:30:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2023-09-11T19:30:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2023-08-20T08:30:00Z', 0, 6);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2023-08-22T17:30:00Z', 2, 5);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2023-07-20T14:30:00Z', 3, 2);

INSERT INTO tb_product (name, price, quantity)
VALUES ('iPhone 13 Pro', 199.9, 55);
INSERT INTO tb_product (name, price, quantity)
VALUES ('iPhone 11', 99.9, 2);
INSERT INTO tb_product (name, price, quantity)
VALUES ('iPad Air', 99.9, 71);
INSERT INTO tb_product (name, price, quantity)
VALUES ('iPad Air Pro', 99.9, 81);
INSERT INTO tb_product (name, price, quantity)
VALUES ('MacBook Air 15 M2', 99.9, 29);
INSERT INTO tb_product (name, price, quantity)
VALUES ('MacBook Air 13 M1', 99.9, 23);

INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 199.9, 1, 1);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (2, 99.9, 5, 1);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 99.9, 2, 2);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 99.9, 4, 2);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (5, 99.9, 6, 3);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (2, 99.9, 5, 3);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 99.9, 3, 4);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 199.9, 1, 4);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (42, 99.9, 6, 5);
